CREATE TABLE feature_flags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_key VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    rollout_percent INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_feature_key UNIQUE (feature_key)
);
