CREATE TABLE feature_targets (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     feature_flag_id BIGINT NOT NULL,
     user_id VARCHAR(255) NOT NULL,
     CONSTRAINT fk_feature_targets_flag
         FOREIGN KEY (feature_flag_id) REFERENCES feature_flags(id)
             ON DELETE CASCADE,
     CONSTRAINT uk_feature_user UNIQUE (feature_flag_id, user_id)
);
