CREATE TABLE flag_change_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_key VARCHAR(255) NOT NULL,
    environment VARCHAR(50) NOT NULL,
    change_type VARCHAR(50) NOT NULL,
    changed_by VARCHAR(255) NOT NULL,
    details VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_change_log_feature_env ON flag_change_logs (feature_key, environment);
CREATE INDEX idx_change_log_created_at ON flag_change_logs (created_at);
